name: Example push

on:
  pull_request:
    types: [synchronize]

jobs:
  example-push-job:
    runs-on: ubuntu-latest
    steps:
      - name: Example push action
        run: |
          echo ${{ github.event_name }}
          echo "PR push action fired"
