name: Example push

on:
  pull_request:
    types: [synchronize]

jobs:
  example-push-job:
    runs-on: ubuntu-latest
    steps:
      - name: Example push action
        run: |

          echo "PR Number ${{ github.event.number }}"
          echo "Branch ${GITHUB_HEAD_REF}"
          echo "PR push action fired"
