name: Example push

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  example-push-job:
    runs-on: ubuntu-latest
    steps:
      - name: Example push action
        run: |
          echo ${{ github.event_name }}
          echo "PR push action fired"
